runtime: java
env: flex

runtime_config:
  operating_system: ubuntu22
  runtime_version: 17
  image: gcr.io/my-project/my-image:v1.10
handlers:
- url: /.*
  script: this field is required, but ignored

manual_scaling:
  instances: 1
